---
platform: linux

image: docker:///ruby#2.1

inputs:
- name: bosh-deployment-resource

outputs:
- name: dropbear-ssh

run:
  path: "/bin/sh"
  args:
  - -exc
  - |
    cd bosh-deployment-resource
    ./scripts/ci
    ./scripts/add_dropbear
    cp ssh ../dropbear-ssh
