---
platform: linux

image: docker:///ruby#2.1

inputs:
- name: bosh-deployment-resource
  path: .

outputs:
- name: dropbear-ssh

run:
  path: "/bin/sh"
  args:
  - -exc
  - |
    scripts/ci
    scripts/add_dropbear
    cp ssh ../dropbear-ssh 
