---
platform: linux

image: docker:///ruby#2.1

inputs:
- name: bosh-deployment-resource

outputs:
- name: docker-build-tmp

run:
  path: "/bin/sh"
  args:
  - -exc
  - |
    cd bosh-deployment-resource
    ./scripts/ci
    ./scripts/add_dropbear
    tar -C . -czhf /tmp/build.tar.gz .
    tar -C ../docker-build-tmp -xzf /tmp/build.tar.gz
